---
- hosts: "{{ Env }}_App_Deployment"
  become: yes
  become_user: deploy
  vars_files:
    - "./vars/variables"
    - "./vars/vault"
  tasks:
    - maven_artifact:
        group_id: "{{ GROUP_ID }}"
        artifact_id: "{{ ARTIFACT_ID }}"
        repository_url: "{{ NEXUS_REPO_URL }}"
        extension: "{{ TEMPLATES_EXTENSION }}"
        username: admin
        version: "{{ VERSION }}"
        password: "{{ NEXUS_REPO_PASS }}"
        dest: "/tmp/{{ ARTIFACT_ID }}-{{ VERSION }}.{{ TEMPLATES_EXTENSION }}"
    - name: Copy Templates file and Past it in Target Server
      shell: |
        export JAVA_HOME="{{ JAVA_HOME }}"
        export PATH=$PATH:$JAVA_HOME/bin      
        JBOSS_HOME="{{ JBOSS_HOME_PATH }}"
        cd $JBOSS_HOME/standalone/data/templates
        jar -xvf "/tmp/{{ ARTIFACT_ID }}-{{ VERSION }}.{{ TEMPLATES_EXTENSION }}"
