---
- hosts: "{{ Env }}_App_Deployment"
  become: yes
  become_user: deploy
  vars_files:
    - "./vars/variables"
    - "./vars/vault"
  tasks:

    - name: Creating obsidian directory
      file:
        path: /tmp/obsidian
        state: directory

    - maven_artifact:
        group_id: "{{ GROUP_ID }}"
        artifact_id: "{{ ARTIFACT_ID }}"
        repository_url: "{{ NEXUS_REPO_URL }}"
        extension: "{{ EXTENSION }}"
        username: admin
        version: "{{ VERSION }}-obsidian"
        password: "{{ NEXUS_REPO_PASS }}"
        dest: "/tmp/obsidian/{{ ARTIFACT_ID }}-{{ VERSION }}-obsidian.{{ EXTENSION }}"
    
    - name: To down the tomcat application
      shell: |
        export JAVA_HOME="{{ JAVA_HOME }}"
        export PATH=$PATH:$JAVA_HOME/bin
        OBSIDIAN_HOME="{{ OBSIDIAN_HOME_PATH }}"
        cd $OBSIDIAN_HOME/bin
        ./shutdown.sh
        echo "OBSIDIAN Application server stopped successfully"
        echo "OBSIDIAN stopped `date +%d%m20%y_%H%M%S`" >> Obsidian_log.txt
        
    - pause:
        seconds: 80
     
    - name: Backup of the Obsidian JAR
      shell: |
        OBSIDIAN_HOME="{{ OBSIDIAN_HOME_PATH }}"
        cd $OBSIDIAN_HOME/webapps/obsidian/WEB-INF/lib/
        mv SMSExecutorJob.jar /app/Backup/SMSExecutorJob_`date +%d_%m_20%y_%H_%M_%S`.jar
        #echo "Backup JAR File"
           
    - name: Copy Property file and Past it in Target tomcat Server
      copy:
        src: "{{ PROPERTIES }}"
        dest: "{{ OBSIDIAN_HOME_PATH }}/conf"   
                 
    - name: To Start the tomcat application
      shell: |
        export JAVA_HOME="{{ JAVA_HOME }}"
        export PATH=$PATH:$JAVA_HOME/bin
        OBSIDIAN_HOME="{{ OBSIDIAN_HOME_PATH }}"
        cd $OBSIDIAN_HOME/logs
        mv catalina.out catalina_`date +%d_%m_20%y_%H_%M_%S`.out
        cd $OBSIDIAN_HOME/bin
        ./startup.sh
        echo "OBSIDIAN Application server stopped successfully"
        echo "OBSIDIAN stopped `date +%d%m20%y_%H%M%S`" >> Obsidian_log.txt
            
    - pause:
        seconds: 10
      
    - name: Deploy the obsidian jar file in tomcat server application
      copy:
        src: "/tmp/obsidian/{{ ARTIFACT_ID }}-{{ VERSION }}-obsidian.{{ EXTENSION }}"
        dest: "{{ OBSIDIAN_HOME_PATH }}/webapps/obsidian/WEB-INF/lib/SMSExecutorJob.jar"
        remote_src: yes   
       
    - name: Clearing War file from tmp
      file:
        path: /tmp/obsidian
        state: absent  
